# Generated by Django 3.2.6 on 2021-08-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
