# Generated by Django 3.2.6 on 2021-08-06 13:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bolt', '0003_auto_20210805_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fqa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolt.userprofile'),
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('shelter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolt.shelter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(blank=True, default=datetime.date.today)),
                ('adoption_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bolt.animal')),
                ('caretaker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolt.caretaker')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
