# Generated by Django 3.2.6 on 2021-08-06 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bolt', '0004_auto_20210806_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_caretaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shelter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolt.shelter'),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='caretaker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caretaker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.DeleteModel(
            name='Caretaker',
        ),
    ]
