# Generated by Django 3.2.6 on 2021-08-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolt', '0006_auto_20210806_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='caretaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caretaker', to='bolt.userprofile'),
        ),
    ]
