# Generated by Django 3.2.6 on 2021-08-07 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolt', '0007_alter_adopt_caretaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_arrival',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
