# Generated by Django 3.2.6 on 2021-08-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolt', '0008_alter_animal_date_of_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolt.shelter'),
        ),
    ]
